networks:
  internal-network:
    name: internal-network

services:
  broker:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - internal-network

  book-service:
    container_name: book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      COM_MALSKYI_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.40:3306/book_db
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/book_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - broker
    networks:
      - internal-network
    volumes:
      - type: bind
        source: D:\docker-logs\book-service
        target: /var/log/book-service

  author-service:
    build:
      context: ./author-service
      dockerfile: Dockerfile
    container_name: author-service
    ports:
      - 8081:8081
    environment:
      SERVER_PORT: 8081
      COM_MALSKYI_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.40:3306/author_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - broker
    networks:
      - internal-network
    volumes:
      - type: bind
        source: D:\docker-logs\author-service
        target: /var/log/author-service