spring:
  application:
    name: server
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/author_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
com:
  malskyi:
    kafka:
      bootstrap:
        servers: localhost:9092
      topic:
        bookBus:
          name: book-events
logging:
  level:
    org:
      springframework: INFO
      apache:
        kafka: INFO
  file:
    name: ./logs/author-service
    pattern: ./logs/author-service
elasticsearch:
  api:
    key: dktFeTNaVUJyeFpzNlp3d1F4Wks6bkU5ZjNjbFJSLXlmNVJKUlNYODE0UQ==
