spring:
  application:
    name: book-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    driver-class-name: com.mysql.cj.jdbc.Driver
com:
  malskyi:
    kafka:
      topic:
        bookBus:
          name: book-events
logging:
  level:
    org:
      springframework: INFO
      apache:
        kafka: INFO