spring:
  application:
    name: book-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/book_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
com:
  malskyi:
    kafka:
      bootstrap:
        servers: localhost:9092
      topic:
        bookBus:
          name: book-events